/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as HudRouteImport } from './routes/hud'
import { Route as EntryRouteImport } from './routes/entry'

const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/entry': typeof EntryRoute
  '/hud': typeof HudRoute
  '/loading': typeof LoadingRoute
}
export interface FileRoutesByTo {
  '/entry': typeof EntryRoute
  '/hud': typeof HudRoute
  '/loading': typeof LoadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/entry': typeof EntryRoute
  '/hud': typeof HudRoute
  '/loading': typeof LoadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/entry' | '/hud' | '/loading'
  fileRoutesByTo: FileRoutesByTo
  to: '/entry' | '/hud' | '/loading'
  id: '__root__' | '/entry' | '/hud' | '/loading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EntryRoute: typeof EntryRoute
  HudRoute: typeof HudRoute
  LoadingRoute: typeof LoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EntryRoute: EntryRoute,
  HudRoute: HudRoute,
  LoadingRoute: LoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
