/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as HudRouteImport } from './routes/hud'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as DeathRouteImport } from './routes/death'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HudRaceLapsRouteRouteImport } from './routes/hud.race-laps/route'
import { Route as HudMenuRouteRouteImport } from './routes/hud.menu/route'
import { Route as HudMenuIndexRouteImport } from './routes/hud.menu/index'
import { Route as HudMenuWorldRouteImport } from './routes/hud.menu/world'
import { Route as HudMenuItemsRouteImport } from './routes/hud.menu/items'
import { Route as HudMenuMatchmakingIndexRouteImport } from './routes/hud.menu/matchmaking/index'
import { Route as HudMenuMatchmakingCreateRouteImport } from './routes/hud.menu/matchmaking/create'

const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DeathRoute = DeathRouteImport.update({
  id: '/death',
  path: '/death',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRaceLapsRouteRoute = HudRaceLapsRouteRouteImport.update({
  id: '/race-laps',
  path: '/race-laps',
  getParentRoute: () => HudRoute,
} as any)
const HudMenuRouteRoute = HudMenuRouteRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => HudRoute,
} as any)
const HudMenuIndexRoute = HudMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HudMenuRouteRoute,
} as any)
const HudMenuWorldRoute = HudMenuWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => HudMenuRouteRoute,
} as any)
const HudMenuItemsRoute = HudMenuItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => HudMenuRouteRoute,
} as any)
const HudMenuMatchmakingIndexRoute = HudMenuMatchmakingIndexRouteImport.update({
  id: '/matchmaking/',
  path: '/matchmaking/',
  getParentRoute: () => HudMenuRouteRoute,
} as any)
const HudMenuMatchmakingCreateRoute =
  HudMenuMatchmakingCreateRouteImport.update({
    id: '/matchmaking/create',
    path: '/matchmaking/create',
    getParentRoute: () => HudMenuRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/death': typeof DeathRoute
  '/entry': typeof EntryRoute
  '/hud': typeof HudRouteWithChildren
  '/loading': typeof LoadingRoute
  '/hud/menu': typeof HudMenuRouteRouteWithChildren
  '/hud/race-laps': typeof HudRaceLapsRouteRoute
  '/hud/menu/items': typeof HudMenuItemsRoute
  '/hud/menu/world': typeof HudMenuWorldRoute
  '/hud/menu/': typeof HudMenuIndexRoute
  '/hud/menu/matchmaking/create': typeof HudMenuMatchmakingCreateRoute
  '/hud/menu/matchmaking/': typeof HudMenuMatchmakingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/death': typeof DeathRoute
  '/entry': typeof EntryRoute
  '/hud': typeof HudRouteWithChildren
  '/loading': typeof LoadingRoute
  '/hud/race-laps': typeof HudRaceLapsRouteRoute
  '/hud/menu/items': typeof HudMenuItemsRoute
  '/hud/menu/world': typeof HudMenuWorldRoute
  '/hud/menu': typeof HudMenuIndexRoute
  '/hud/menu/matchmaking/create': typeof HudMenuMatchmakingCreateRoute
  '/hud/menu/matchmaking': typeof HudMenuMatchmakingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/death': typeof DeathRoute
  '/entry': typeof EntryRoute
  '/hud': typeof HudRouteWithChildren
  '/loading': typeof LoadingRoute
  '/hud/menu': typeof HudMenuRouteRouteWithChildren
  '/hud/race-laps': typeof HudRaceLapsRouteRoute
  '/hud/menu/items': typeof HudMenuItemsRoute
  '/hud/menu/world': typeof HudMenuWorldRoute
  '/hud/menu/': typeof HudMenuIndexRoute
  '/hud/menu/matchmaking/create': typeof HudMenuMatchmakingCreateRoute
  '/hud/menu/matchmaking/': typeof HudMenuMatchmakingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/death'
    | '/entry'
    | '/hud'
    | '/loading'
    | '/hud/menu'
    | '/hud/race-laps'
    | '/hud/menu/items'
    | '/hud/menu/world'
    | '/hud/menu/'
    | '/hud/menu/matchmaking/create'
    | '/hud/menu/matchmaking/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/death'
    | '/entry'
    | '/hud'
    | '/loading'
    | '/hud/race-laps'
    | '/hud/menu/items'
    | '/hud/menu/world'
    | '/hud/menu'
    | '/hud/menu/matchmaking/create'
    | '/hud/menu/matchmaking'
  id:
    | '__root__'
    | '/'
    | '/death'
    | '/entry'
    | '/hud'
    | '/loading'
    | '/hud/menu'
    | '/hud/race-laps'
    | '/hud/menu/items'
    | '/hud/menu/world'
    | '/hud/menu/'
    | '/hud/menu/matchmaking/create'
    | '/hud/menu/matchmaking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeathRoute: typeof DeathRoute
  EntryRoute: typeof EntryRoute
  HudRoute: typeof HudRouteWithChildren
  LoadingRoute: typeof LoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/death': {
      id: '/death'
      path: '/death'
      fullPath: '/death'
      preLoaderRoute: typeof DeathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud/race-laps': {
      id: '/hud/race-laps'
      path: '/race-laps'
      fullPath: '/hud/race-laps'
      preLoaderRoute: typeof HudRaceLapsRouteRouteImport
      parentRoute: typeof HudRoute
    }
    '/hud/menu': {
      id: '/hud/menu'
      path: '/menu'
      fullPath: '/hud/menu'
      preLoaderRoute: typeof HudMenuRouteRouteImport
      parentRoute: typeof HudRoute
    }
    '/hud/menu/': {
      id: '/hud/menu/'
      path: '/'
      fullPath: '/hud/menu/'
      preLoaderRoute: typeof HudMenuIndexRouteImport
      parentRoute: typeof HudMenuRouteRoute
    }
    '/hud/menu/world': {
      id: '/hud/menu/world'
      path: '/world'
      fullPath: '/hud/menu/world'
      preLoaderRoute: typeof HudMenuWorldRouteImport
      parentRoute: typeof HudMenuRouteRoute
    }
    '/hud/menu/items': {
      id: '/hud/menu/items'
      path: '/items'
      fullPath: '/hud/menu/items'
      preLoaderRoute: typeof HudMenuItemsRouteImport
      parentRoute: typeof HudMenuRouteRoute
    }
    '/hud/menu/matchmaking/': {
      id: '/hud/menu/matchmaking/'
      path: '/matchmaking'
      fullPath: '/hud/menu/matchmaking/'
      preLoaderRoute: typeof HudMenuMatchmakingIndexRouteImport
      parentRoute: typeof HudMenuRouteRoute
    }
    '/hud/menu/matchmaking/create': {
      id: '/hud/menu/matchmaking/create'
      path: '/matchmaking/create'
      fullPath: '/hud/menu/matchmaking/create'
      preLoaderRoute: typeof HudMenuMatchmakingCreateRouteImport
      parentRoute: typeof HudMenuRouteRoute
    }
  }
}

interface HudMenuRouteRouteChildren {
  HudMenuItemsRoute: typeof HudMenuItemsRoute
  HudMenuWorldRoute: typeof HudMenuWorldRoute
  HudMenuIndexRoute: typeof HudMenuIndexRoute
  HudMenuMatchmakingCreateRoute: typeof HudMenuMatchmakingCreateRoute
  HudMenuMatchmakingIndexRoute: typeof HudMenuMatchmakingIndexRoute
}

const HudMenuRouteRouteChildren: HudMenuRouteRouteChildren = {
  HudMenuItemsRoute: HudMenuItemsRoute,
  HudMenuWorldRoute: HudMenuWorldRoute,
  HudMenuIndexRoute: HudMenuIndexRoute,
  HudMenuMatchmakingCreateRoute: HudMenuMatchmakingCreateRoute,
  HudMenuMatchmakingIndexRoute: HudMenuMatchmakingIndexRoute,
}

const HudMenuRouteRouteWithChildren = HudMenuRouteRoute._addFileChildren(
  HudMenuRouteRouteChildren,
)

interface HudRouteChildren {
  HudMenuRouteRoute: typeof HudMenuRouteRouteWithChildren
  HudRaceLapsRouteRoute: typeof HudRaceLapsRouteRoute
}

const HudRouteChildren: HudRouteChildren = {
  HudMenuRouteRoute: HudMenuRouteRouteWithChildren,
  HudRaceLapsRouteRoute: HudRaceLapsRouteRoute,
}

const HudRouteWithChildren = HudRoute._addFileChildren(HudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeathRoute: DeathRoute,
  EntryRoute: EntryRoute,
  HudRoute: HudRouteWithChildren,
  LoadingRoute: LoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
