/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as HudRouteImport } from './routes/hud'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as DeathRouteImport } from './routes/death'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HudMenuRouteImport } from './routes/hud.menu'
import { Route as HudMenuIndexRouteImport } from './routes/hud.menu.index'
import { Route as HudMenuWeaponsRouteImport } from './routes/hud.menu.weapons'
import { Route as HudMenuLobbiesRouteImport } from './routes/hud.menu.lobbies'

const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DeathRoute = DeathRouteImport.update({
  id: '/death',
  path: '/death',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HudMenuRoute = HudMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => HudRoute,
} as any)
const HudMenuIndexRoute = HudMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HudMenuRoute,
} as any)
const HudMenuWeaponsRoute = HudMenuWeaponsRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => HudMenuRoute,
} as any)
const HudMenuLobbiesRoute = HudMenuLobbiesRouteImport.update({
  id: '/lobbies',
  path: '/lobbies',
  getParentRoute: () => HudMenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/death': typeof DeathRoute
  '/entry': typeof EntryRoute
  '/hud': typeof HudRouteWithChildren
  '/loading': typeof LoadingRoute
  '/hud/menu': typeof HudMenuRouteWithChildren
  '/hud/menu/lobbies': typeof HudMenuLobbiesRoute
  '/hud/menu/weapons': typeof HudMenuWeaponsRoute
  '/hud/menu/': typeof HudMenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/death': typeof DeathRoute
  '/entry': typeof EntryRoute
  '/hud': typeof HudRouteWithChildren
  '/loading': typeof LoadingRoute
  '/hud/menu/lobbies': typeof HudMenuLobbiesRoute
  '/hud/menu/weapons': typeof HudMenuWeaponsRoute
  '/hud/menu': typeof HudMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/death': typeof DeathRoute
  '/entry': typeof EntryRoute
  '/hud': typeof HudRouteWithChildren
  '/loading': typeof LoadingRoute
  '/hud/menu': typeof HudMenuRouteWithChildren
  '/hud/menu/lobbies': typeof HudMenuLobbiesRoute
  '/hud/menu/weapons': typeof HudMenuWeaponsRoute
  '/hud/menu/': typeof HudMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/death'
    | '/entry'
    | '/hud'
    | '/loading'
    | '/hud/menu'
    | '/hud/menu/lobbies'
    | '/hud/menu/weapons'
    | '/hud/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/death'
    | '/entry'
    | '/hud'
    | '/loading'
    | '/hud/menu/lobbies'
    | '/hud/menu/weapons'
    | '/hud/menu'
  id:
    | '__root__'
    | '/'
    | '/death'
    | '/entry'
    | '/hud'
    | '/loading'
    | '/hud/menu'
    | '/hud/menu/lobbies'
    | '/hud/menu/weapons'
    | '/hud/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeathRoute: typeof DeathRoute
  EntryRoute: typeof EntryRoute
  HudRoute: typeof HudRouteWithChildren
  LoadingRoute: typeof LoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/death': {
      id: '/death'
      path: '/death'
      fullPath: '/death'
      preLoaderRoute: typeof DeathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud/menu': {
      id: '/hud/menu'
      path: '/menu'
      fullPath: '/hud/menu'
      preLoaderRoute: typeof HudMenuRouteImport
      parentRoute: typeof HudRoute
    }
    '/hud/menu/': {
      id: '/hud/menu/'
      path: '/'
      fullPath: '/hud/menu/'
      preLoaderRoute: typeof HudMenuIndexRouteImport
      parentRoute: typeof HudMenuRoute
    }
    '/hud/menu/weapons': {
      id: '/hud/menu/weapons'
      path: '/weapons'
      fullPath: '/hud/menu/weapons'
      preLoaderRoute: typeof HudMenuWeaponsRouteImport
      parentRoute: typeof HudMenuRoute
    }
    '/hud/menu/lobbies': {
      id: '/hud/menu/lobbies'
      path: '/lobbies'
      fullPath: '/hud/menu/lobbies'
      preLoaderRoute: typeof HudMenuLobbiesRouteImport
      parentRoute: typeof HudMenuRoute
    }
  }
}

interface HudMenuRouteChildren {
  HudMenuLobbiesRoute: typeof HudMenuLobbiesRoute
  HudMenuWeaponsRoute: typeof HudMenuWeaponsRoute
  HudMenuIndexRoute: typeof HudMenuIndexRoute
}

const HudMenuRouteChildren: HudMenuRouteChildren = {
  HudMenuLobbiesRoute: HudMenuLobbiesRoute,
  HudMenuWeaponsRoute: HudMenuWeaponsRoute,
  HudMenuIndexRoute: HudMenuIndexRoute,
}

const HudMenuRouteWithChildren =
  HudMenuRoute._addFileChildren(HudMenuRouteChildren)

interface HudRouteChildren {
  HudMenuRoute: typeof HudMenuRouteWithChildren
}

const HudRouteChildren: HudRouteChildren = {
  HudMenuRoute: HudMenuRouteWithChildren,
}

const HudRouteWithChildren = HudRoute._addFileChildren(HudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeathRoute: DeathRoute,
  EntryRoute: EntryRoute,
  HudRoute: HudRouteWithChildren,
  LoadingRoute: LoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
