services:
  server:
    image: ghcr.io/cyber-mp/freeroam:latest
    env_file: .env
    environment:
      NODE_ENV: production
      IS_DOCKER: "true"
    stdin_open: true
    tty: true
    volumes:
      - ./cache:/cybermp/cache
      - ./crashdumps:/cybermp/crashdumps
      - ./logs:/cybermp/logs
    ports:
      - ${PORT:-2077}:2077/tcp
      - ${PORT:-2077}:2077/udp

volumes:
  cache:
  crashdumps:
