services:
  server:
    container_name: cybermp-freeroam
    image: ghcr.io/cyber-mp/server:latest
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
      IS_DOCKER: "true"
    volumes:
      - ./server.toml:/cybermp/server.toml
      - ./resources:/cybermp/resources
      - ./crashdumps:/cybermp/crashdumps
    ports:
      - 2077:2077/tcp
      - 2077:2077/udp
