import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { useFocus } from '@/hooks/use-focus';
import { client } from '@/rpc';

export const Route = createFileRoute('/death')({
  component: RouteComponent,
});

const DEATH_MESSAGES = [
  {
    title: 'Potracheno',
    description: 'Even legends eventually find their dick...',
  },
  {
    title: 'You Perished',
    description: 'The flame flickers out in the cold dark.',
  },
  {
    title: 'Skill Issue',
    description: "Fate is a cruel mistress, but she's also faster than you.",
  },
  {
    title: 'Rest in Pieces',
    description: 'Your journey was long, but my dick was longer.',
  },
  {
    title: 'Game Over',
    description: 'Insert coin to continue... oh wait, this shit is corny.',
  },
  {
    title: 'Flatline',
    description:
      'Well... even legends find their end. (crony asf cuz generated by AI)',
  },
];

function RouteComponent() {
  // Randomly select a message once on mount
  const message = useMemo(() => {
    return DEATH_MESSAGES[Math.floor(Math.random() * DEATH_MESSAGES.length)];
  }, []);

  const navigate = useNavigate();

  useFocus();

  const spawnOnBase = () => {
    client.spawn.spawnOnBase.trigger();
    navigate({ to: '/hud' });
  };

  const spawnOnLocation = () => {
    client.spawn.spawnOnLocation.trigger();
    navigate({ to: '/hud' });
  };

  const [randomNumber] = useState(Math.random());

  console.log("RERENDER '/death'", randomNumber);

  return (
    <div className="fixed inset-0 flex flex-col items-center justify-center bg-[#00000060]  text-white font-serif p-4">
      {/* Background Overlay */}
      <div className="absolute inset-0 z-[-1] backdrop-grayscale bg-[#00000040]" />

      {/* Death Message */}
      <div className="text-center mb-12 animate-in fade-in zoom-in duration-1000">
        <h1 className="text-6xl md:text-8xl font-black tracking-tighter text-red-700 uppercase drop-shadow-[0_0_20px_rgba(185,28,28,0.6)]">
          {message.title}
        </h1>
        <p className="mt-4 text-xl md:text-2xl italic text-gray-400 animate-pulse">
          "{message.description}"
        </p>
      </div>

      {/* Actions using your custom Button component */}
      <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md relative z-10">
        <Button
          onClick={spawnOnLocation}
          variant="outline"
          size="lg"
          className="flex-1 uppercase"
        >
          Spawn at location
        </Button>
        <Button
          onClick={spawnOnBase}
          variant="destructive"
          size="lg"
          className="flex-1 uppercase"
        >
          Spawn at base
        </Button>
      </div>

      {/* Decorative Scanlines */}
      <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_2px,3px_100%]" />

      <span className="absolute top-0 left-0 z-9999999">{randomNumber}</span>
    </div>
  );
}
