author = "terminaate"
description = "cybermp-ts-resource-template"
version = "1.0.0"

# ui_page = "http://localhost:5173"

# client_script = "./client/dist/index.iife.js"
server_script = ["./server/dist/index.js"]

# use_game_natives = "true"
