export const CyberpsychoWeapons = {
  'Items.Preset_Silverhand_3516': 'Silverhand 3516',
  'Items.Preset_Nue_Maiko': 'Death and Taxes',
  'Items.Preset_Yukimura_Default': 'HJKE-11 Yukimura',
  'Items.Preset_Senkoh_Default': 'Senkoh LX',
  'Items.Preset_Fanged_Axe_Default': 'Claw',
  'Items.Preset_Katana_Saburo': 'Satori',
  'Items.Preset_Saratoga_Raffen': 'Problem Solver',
  'Items.Preset_Overture_Cassidy': 'Amnesty',
  'Items.Legendary_Zhuo_Eight_Star': 'Ba Xing Chong',
  'Items.Preset_Tactician_Dino': 'Bloody Maria',
  'Items.Preset_Neurotoxin_Knife_Iconic': 'Blue Fang',
  'Items.Preset_Katana_GoG': 'Black Unicorn',
  'Items.Preset_Katana_Cocktail': 'Cocktail Stick',
  'Items.Preset_Carnage_Edgerunners': 'Guts',
  'Items.Preset_Masamune_Rogue': 'Prejudice',
  'Items.Legendary_Ajax_Moron': 'Moron Labe',
  'Items.Preset_Dian_Yinglong': 'Yinglong',
  // 'Items.w_melee_boss_hammer': "Sasquatch's Hammer",
  'Items.Preset_Dildo_Stout': 'Sir John Phallustiff',
  'Items.Preset_MA70_Default': 'MA70 HB',
  'Items.Preset_Kolac_Tiny_Mike': 'Hypercritical',
  'Items.Preset_Grad_Buck': "O'Five",
};
