#:schema https://schemas.cyber.mp/resource/schema.json

server_script = ["./server.js"]
client_script = ["./client.js"]
file = ["./assets/in_world_navigation.archive"]

ui_page = "http://localhost:5173"

use_game_natives = "true"

hotreload = true
