#:schema https://schemas.cyber.mp/resource/schema.json

server_script = ["./server.js"]
client_script = ["./client.js"]
file = [
  "./assets/in_world_navigation.archive",
  "./browser/*",
  "./browser/assets/*"
]

ui_page = "cefview://freeroam/browser/index.html"

use_game_natives = "true"

hotreload = true
