import { injectable } from 'inversify';
import { mp } from '../../mp';

export const ITEM_SPAWNER_KEYS = [
  // weapons
  'Preset_Lexington_Toygun',
  'Preset_Fanged_Axe_Default',
  'Preset_Katana_Saburo',
  'Preset_Overture_Cassidy',
  'Legendary_Zhuo_Eight_Star',
  'Preset_Neurotoxin_Knife_Iconic',
  'Preset_Katana_Cocktail',
  'Preset_Carnage_Edgerunners',
  'Preset_Dian_Yinglong',
  'w_melee_boss_hammer',
  'GrenadeOzobsNose',
  'Preset_Dildo_Stout',
  'Preset_Nue_Maiko',
  'Preset_Silverhand_3516',
  'Preset_Yukimura_Default',
  'Preset_Senkoh_Default',
  'Preset_Borg4a_HauntedGun',
  'Preset_Tactician_Dino',
  'Preset_Masamune_Rogue',
  'Legendary_Ajax_Moron',
  'Preset_MA70_Default',
  'Preset_Kolac_Tiny_Mike',
  'Preset_Grad_Buck',
  'Preset_Katana_GoG',
  // implants
  'AdvancedCamilloRamManagerLegendaryPlus',
  'AdvancedBioConductorsLegendaryPlus',
  'AdvancedSubdermalCoProcessorLegendaryPlus',
  'AdvancedStrongArmsLegendaryPlus',
  'AdvancedMantisBladesLegendaryPlus',
  'AdvancedNanoWiresLegendaryPlus',
  'AdvancedProjectileLauncherLegendaryPlus',
  'AdvancedKiroshiOpticsBareLegendaryPlus',
  'AdvancedT1000LegendaryPlus',
  'AdvancedEndoskeletonLegendaryPlus',
  'AdvancedBoneMarrowCellsLegendaryPlus',
  'AdvancedRapidMuscleNurishLegendaryPlus',
  'AdvancedTitaniumInfusedBonesLegendaryPlus',
  'AdvancedPainDistributorLegendaryPlus',
  'AdvancedSmartLinkLegendaryPlus',
  'AdvancedPowerGripLegendaryPlus',
  'AdvancedKnifeSharpenerLegendaryPlus',
  'AdvancedMicroGeneratorLegendaryPlus',
  'AdvancedJointLockLegendaryPlus',
  'AdvancedNeoFiberLegendaryPlus',
  'AdvancedTyrosineInjectorLegendaryPlus',
  'AdvancedOilDispenserLegendaryPlus',
  'AdvancedCatchMeIfYouCanLegendaryPlus',
  'AdvancedSecondHeartLegendaryPlus',
  'AdvancedCyberRotorsLegendaryPlus',
  'AdvancedHealOnKillLegendaryPlus',
  'AdvancedDischargeConnectorLegendaryPlus',
  'AdvancedShockAbsorberLegendaryPlus',
  'AdvancedBloodPumpLegendaryPlus',
  'AdvancedBiomonitorLegendaryPlus',
  'AdvancedStaminaRegenBoosterLegendaryPlus',
  'AdvancedBoringPlatingLegendaryPlus',
  'AdvancedElectroshockMechanismLegendaryPlus',
  'AdvancedChargeSystemLegendaryPlus',
  'AdvancedProximityReducerLegendaryPlus',
  'AdvancedBloodDepleterLegendaryPlus',
  'AdvancedPainReductorLegendaryPlus',
  'AdvancedWeirdTankyPlatingLegendaryPlus',
  'AdvancedBoostedTendonsLegendaryPlus',
  'AdvancedCatPawsLegendaryPlus',
  'AdvancedJenkinsTendonsLegendaryPlus',
  'AdvancedReinforcedMusclesLegendaryPlus',
  'AdvancedBerserkC3MK5Plus',
  'AdvancedBerserkC1MK4Plus',
  'AdvancedBerserkC4MK5Plus',
  'AdvancedBerserkC2MK4Plus',
  // clothes
  'Q303_mask_h1',
  'Q005_Johnny_Glasses',
  'SQ031_Samurai_Jacket',
  'Q005_Johnny_Shirt',
  'Q005_Johnny_Pants',
  'Q005_Johnny_Shoes',
  'GrenadeFragLegendaryPlus',
  'GrenadeEMPLegendaryPlus',
  'BlackLaceV1',
  'Blackmarket_MemoryBooster',
  'Blackmarket_StaminaBooster',
  'BonesMcCoy70VLegendaryPlus',
  'FirstAidWhiffVLegendaryPlus',
  'OxyBooster',
  'HealthBooster',
  'Visor_01_basic_02',
  'Visor_02_basic_01',
  'Tech_01_rich_01',
  'Tech_02_basic_02',
  'Vest_04_rich_02',
  'Vest_02_rich_02',
  'SQ030_MaxTac_Chest',
  'Q115_Custom_Predator_Armor',
  'Cop_01_Set_Jacket',
  'Twitch_Drop_Specs',
  'Vest_08_basic_01',
  'TightJumpsuit_01_rich_02',
  'TightJumpsuit_01_basic_01',
  'Vest_24_basic_01',
  'Vest_21_rich_03',
  'FormalPants_02_basic_01',
  'Undershirt_03_basic_02',
  'Tshirt_12_old_04',
  'Tshirt_12_basic_01',
  'FormalSkirt_01_basic_02',
  'Media_01_Set_Pants',
  'Pants_03_basic_03',
  'Pants_03_rich_03',
  'Pants_07_old_02',
  'Pants_11_old_02',
  'Boots_03_old_01',
  'Boots_07_basic_01',
  'Boots_09_old_01',
  'Boots_09_rich_03',
  'CasualShoes_04_basic_02',
  'Cop_01_Set_Boots',
  'Cop_01_Set_Boots',
  'FormalShoes_02_rich_01',
  'FormalShoes_03_rich_02',
  'SQ030_Diving_Suit',
  'Trauma_Team_Outfit',
] as const;

type ItemSpawnerKey = (typeof ITEM_SPAWNER_KEYS)[number];

@injectable()
export class ItemSpawnerService {
  spawnItem(key: ItemSpawnerKey) {
    mp.game.AddToInventory(`Items.${key}`, 1);
  }
}
