import { injectable } from 'inversify';
import { mp } from '../../mp';

export const ITEM_SPAWNER_KEYS = [
  'Preset_Lexington_Toygun',
  'Preset_Fanged_Axe_Default',
  'Preset_Katana_Saburo',
  'Preset_Achilles_Collectible',
  'Preset_VB_Axe',
  'Preset_Pozhar_AirDrop',
  'Preset_Kenshin_Spy',
  'Preset_Overture_Cassidy',
  'Preset_Crusher_Amazon',
  'Legendary_Zhuo_Eight_Star',
  'Preset_Baseball_Bat_Malina',
  'Preset_Neurotoxin_Knife_Iconic',
  'Preset_Grad_AirDrop',
  'Preset_Umbra_Bebe',
  'Preset_Katana_Cocktail',
  'Preset_Carnage_Edgerunners',
  'Preset_Sword_Witcher',
  'Preset_Baton_Murphy',
  'Preset_Dian_Yinglong',
  'w_melee_boss_hammer',
  'Preset_Ajax_Amazon',
  'GrenadeOzobsNose',
  'Preset_Dildo_Stout',

  'AdvancedCamilloRamManagerLegendaryPlusPlus',

  'Q303_mask_h1',
  'Q005_Johnny_Glasses',
  'SQ031_Samurai_Jacket',
  'Q005_Johnny_Shirt',
  'Q005_Johnny_Pants',
  'Q005_Johnny_Shoes',
  'GrenadeFragLegendaryPlus',
  'GrenadeEMPLegendaryPlus',
  'BlackLaceV1',
  'Blackmarket_MemoryBooster',
  'Blackmarket_StaminaBooster',
  'BonesMcCoy70VLegendaryPlus',
  'FirstAidWhiffVLegendaryPlus',
  'OxyBooster',
  'HealthBooster',
  'Visor_01_basic_02',
  'Visor_02_basic_01',
  'Tech_01_rich_01',
  'Tech_02_basic_02',
  'Vest_04_rich_02',
  'Vest_02_rich_02',
  'SQ030_MaxTac_Chest',
  'Q115_Custom_Predator_Armor',
  'Cop_01_Set_Jacket',
  'Twitch_Drop_Specs',
  'Vest_08_basic_01',
  'TightJumpsuit_01_rich_02',
  'TightJumpsuit_01_basic_01',
  'Vest_24_basic_01',
  'Vest_21_rich_03',
  'FormalPants_02_basic_01',
  'Undershirt_03_basic_02',
  'Tshirt_12_old_04',
  'Tshirt_12_basic_01',
  'FormalSkirt_01_basic_02',
  'Media_01_Set_Pants',
  'Pants_03_basic_03',
  'Pants_03_rich_03',
  'Pants_07_old_02',
  'Pants_11_old_02',
  'Boots_03_old_01',
  'Boots_07_basic_01',
  'Boots_09_old_01',
  'Boots_09_rich_03',
  'CasualShoes_04_basic_02',
  'Cop_01_Set_Boots',
  'Cop_01_Set_Boots',
  'FormalShoes_02_rich_01',
  'FormalShoes_03_rich_02',
  'SQ030_Diving_Suit',
  'Trauma_Team_Outfit',
] as const;

type ItemSpawnerKey = (typeof ITEM_SPAWNER_KEYS)[number];

@injectable()
export class ItemSpawnerService {
  spawnItem(key: ItemSpawnerKey) {
    mp.game.AddToInventory(`Items.${key}`, 1);
  }
}
